language: node_js
node_js:
- 10
- 11
- 12
- 13
script:
- yarn lint
- yarn test
deploy:
  provider: npm
  email: asmirnov@virgilsecurity.com
  api_key:
    secure: HEjX9UD1SKeivKlE1wGek0WAtz6uFYiYMjRRW6CZuIE940jVj6T2jZbkf+Dw5faAdmEUuD6Y0QOcCcsJm/YDOoSWDywMaBqz7Xozk7DeQQfgAtQ6wWLIbIJrttz/TYdaz+F/V0Le4Yzlrr2kpHzy9/pLPE4rBCrUfFd5+hIcd/2rcg9W40203YRRLmES5+NDeUFRvZxHqhnxZxW15Vei8Utx0d3f69GHI2y3hJCKh/7T9svJnIUXxHbVYjXQ6a+W9nCO5xFC8w6SE9vEsyd8yOfd0PAebnCIXJIEuzSj2W0z5VlMsBHd4gvcVKqusL0YiNr3+LQf/bADBQPGjSt8EOIUd9bWMoKhR+3ZTLoSnM3gDe8P27Uk3xuvAqk7oOc1t9GZewe4uq1NaEWs57naR0Gdi/c1mPQuSc1zyZtMnk4IqlbkYCNOzMgCtoKPLRL9Yv/RmxbE/bB1fNkh44PUFqopGnewjhNxKiKPfAibIKnJNPAXw3vsHVpx94LexzowpsU3INZ++7sUcbHHEQQchua8Yyx6L0WKX9CfchMqo708e4G+CEeJIDF4GfmGkX8WwFoBV3x+1PZ5jLNJG67H+7eUYf7Wte883LgCYry428JChMXlajVyK6kHEHJwOcbUlX/qPtxo4ceclCoMRq+EV9W8bovA42z/RniHnEMbc2M=
  on:
    tags: true
    repo: VirgilSecurity/virgil-key-storage-rn
    node: 13
